### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by Battiachpro** [IRPsimp/IPABundler#1]
Hey, 
So I'm completely new to any kind of programming and I tried to use the apptoipa thing and I've had a lot of trouble with it, probably due to me being unexperienced.
My CMD says "'apptoipa' is not recognized as an internal or external command,
operable program or batch file."
Do you know how I can make things work?
Thanks in advance

**Comment by deqline** [comment]
Hello, in order to run it you must navigate within cmd to the directory where your .ipa/.app file resides and you must also copy the apptoipa exe file inside the same directory￼.
