### ISSUE TITLE
It says access is denied

### ISSUE THREAD

**Issue by Stablows** [IRPsimp/IPABundler#2]
When i type apptoipa <file> [-d] and type my file name it says "Access is denied.".  I have the apptoipa exe in my file and everything. Please help.

**Comment by deqline** [comment]
Hello, are you in the correct directory where your file is located? if yes, where are you typing this line, in cmd?
Check if your `.ipa` file is inside a directory where you have access (i.e you're able to create files). 
You could try running cmd as admin and then try again. If this still does not work then after typing the command enter `echo %errorlevel%` and send me the number.
