### ISSUE TITLE
The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by carterge** [IRPsimp/IPABundler#5]
When i go to make my IPA into a .app it gives me the error [The syntax of the command is incorrect.]

**Comment by deqline** [comment]
Keep in mind, this program only works on windows.

If you are on windows then:
1. download the program executable from this [link](https://github.com/deqline/IPABundler/releases/tag/3.0)?
2. create a directoy and move `apptoipa.exe` along with the ipa file inside it
3. open command prompt and navigate to this directory and type `apptoipa.exe file.ipa`
